// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SplitApi.Models;

namespace splitapi.Migrations
{
    [DbContext(typeof(SplitContext))]
    partial class SplitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("SplitApi.Models.Account", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("accountId")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnName("accountName")
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("modifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnName("userId");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("SplitApi.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("categoryId")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnName("categoryName")
                        .HasColumnType("character varying(25)");

                    b.Property<string>("CategoryType")
                        .IsRequired()
                        .HasColumnName("categoryType")
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnName("userId");

                    b.HasKey("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SplitApi.Models.SplitPayment", b =>
                {
                    b.Property<Guid>("SplitPaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("splitPaymentId")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("money");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("modifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PayeeId")
                        .HasColumnName("payeeId");

                    b.Property<Guid>("TransactionId")
                        .HasColumnName("transactionId");

                    b.HasKey("SplitPaymentId");

                    b.HasIndex("PayeeId");

                    b.HasIndex("TransactionId");

                    b.ToTable("SplitPayments");
                });

            modelBuilder.Entity("SplitApi.Models.Transaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("transactionId")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid?>("AccountInId")
                        .HasColumnName("accountInId");

                    b.Property<Guid?>("AccountOutId")
                        .HasColumnName("accountOutId");

                    b.Property<decimal?>("Amount")
                        .HasColumnName("amount")
                        .HasColumnType("money");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsShared")
                        .HasColumnName("isShared");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("modifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("transactionDate")
                        .HasColumnType("date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<Guid?>("TransactionPartyId")
                        .HasColumnName("transactionPartyId");

                    b.Property<Guid?>("UserId")
                        .HasColumnName("userId");

                    b.HasKey("TransactionId");

                    b.HasIndex("AccountInId");

                    b.HasIndex("AccountOutId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TransactionPartyId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("SplitApi.Models.TransactionParty", b =>
                {
                    b.Property<Guid>("TransactionPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("transactionPartyId")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("DefaultCategoryId")
                        .HasColumnName("defaultCategoryId");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("modifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TransactionPartyName")
                        .IsRequired()
                        .HasColumnName("transactionPartyName")
                        .HasColumnType("character varying(25)");

                    b.HasKey("TransactionPartyId");

                    b.HasIndex("DefaultCategoryId");

                    b.ToTable("TransactionParties");
                });

            modelBuilder.Entity("SplitApi.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("userId")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool?>("ConfirmedEmail")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("confirmedEmail")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("createdOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("email")
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .HasColumnName("firstName")
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsRegistered")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("isRegistered")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnName("lastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnName("lastName")
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ModifiedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("modifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnName("passwordHash");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnName("passwordSalt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("character varying(20)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasName("User_email_key");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasName("User_username_key");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SplitApi.Models.Account", b =>
                {
                    b.HasOne("SplitApi.Models.User", "User")
                        .WithMany("Account")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Account_userId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SplitApi.Models.Category", b =>
                {
                    b.HasOne("SplitApi.Models.User", "User")
                        .WithMany("Category")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Category_userId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SplitApi.Models.SplitPayment", b =>
                {
                    b.HasOne("SplitApi.Models.User", "Payee")
                        .WithMany("SplitPayment")
                        .HasForeignKey("PayeeId")
                        .HasConstraintName("SplitPayment_payeeId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SplitApi.Models.Transaction", "Transaction")
                        .WithMany("SplitPayment")
                        .HasForeignKey("TransactionId")
                        .HasConstraintName("SplitPayment_transactionId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SplitApi.Models.Transaction", b =>
                {
                    b.HasOne("SplitApi.Models.Account", "AccountIn")
                        .WithMany("TransactionAccountIn")
                        .HasForeignKey("AccountInId")
                        .HasConstraintName("Transaction_accountInId_fkey");

                    b.HasOne("SplitApi.Models.Account", "AccountOut")
                        .WithMany("TransactionAccountOut")
                        .HasForeignKey("AccountOutId")
                        .HasConstraintName("Transaction_accountOutId_fkey");

                    b.HasOne("SplitApi.Models.Category", "Category")
                        .WithMany("Transaction")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("Transaction_categoryId_fkey")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitApi.Models.TransactionParty", "TransactionParty")
                        .WithMany("Transaction")
                        .HasForeignKey("TransactionPartyId")
                        .HasConstraintName("Transaction_transactionPartyId_fkey")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SplitApi.Models.User", "User")
                        .WithMany("Transaction")
                        .HasForeignKey("UserId")
                        .HasConstraintName("Transaction_userId_fkey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SplitApi.Models.TransactionParty", b =>
                {
                    b.HasOne("SplitApi.Models.Category", "DefaultCategory")
                        .WithMany("TransactionParty")
                        .HasForeignKey("DefaultCategoryId")
                        .HasConstraintName("TransactionParty_defaultCategoryId_fkey")
                        .OnDelete(DeleteBehavior.SetNull);
                });
#pragma warning restore 612, 618
        }
    }
}
